export const localeConfig: {[key: string]: string} = {
    "CHAT_ROOM": "Chat Room",
    "LEAVE_ROOM": "Leave Room",
    "TYPE_YOUR_MESSAGE": "Type your message...",
    "SEND": "Send",
    "IS_": " is ", 
    "JOIN_OR_CREATE_A_CHAT_ROOM": "Join or Create a Chat Room",
    "CREATE_NEW_ROOM": "Create New Room",
    "NICKNAME": "Nickname",
    "YOUR_NICKNAME": "Your Nickname",
    "OR": "OR",
    "JOIN_EXISTING_ROOM": "Join Existing Room",
    "ROOM_ID": "Room ID",
    "ENTER_ROOM_ID": "Enter Room ID",
    "JOIN_ROOM": "Join Room",
    "PLEASE_ENTER_A_NICKNAME_TO_CREATE_A_ROOM.": "Please enter a nickname to create a room.",
    "PLEASE_ENTER_A_ROOM_ID_AND_A_NICKNAME_TO_JOIN.": "Please enter a room ID and a nickname to join.",
    "FAILED_TO_CREATE_ROOM": "Failed to create room.",
  };